### ISSUE TITLE
Fix navbar vertical spacing

### ISSUE THREAD

**Issue by augusthalverson** [augusthalverson/fight-for-the-climate#11]

**Comment by jascaniojah** [comment]
I would like to work on this one @augusthalverson

**Comment by augusthalverson** [comment]
Excellent! I'm planning on changing the menu-items and adding fontawesome icons at some point. Not sure how the `<i>` tags will affect spacing fixes. That can be tackled down the road.

**Comment by jascaniojah** [comment]
@augusthalverson i couldnt start this project, build fails

**Comment by augusthalverson** [comment]
> @augusthalverson i couldnt start this project, build fails

Any insight about why? Any error messages?

**Comment by jascaniojah** [comment]
@augusthalverson MongoDB was crashing, i re started and it works. Any comments about how this should be fix?

**Comment by augusthalverson** [comment]
> @augusthalverson MongoDB was crashing, i re started and it works. Any comments about how this should be fix?

Not exactly sure what you mean. Everything looks great though!
