### ISSUE TITLE
add dynamic page titles

### ISSUE THREAD

**Issue by augusthalverson** [augusthalverson/fight-for-the-climate#5]
pass a `page title` attribute into each `ejs` `view`

**Comment by Willumz** [comment]
Hi @augusthalverson, this sounds great. I'd like to do it.
When passing the title from `app.js`, what would you want the titles to be?

**Comment by augusthalverson** [comment]
- On the fact show pages, maybe `headline` (maybe truncated, or maybe just the whole thing)
- On the source show pages, the `name_long` of the source, probably.
- Everywhere else, just logical things like "Home | fight-for-the-climate", or whatever seems appropriate. I trust you ;)
